Update

diff --git a/bin/currency-conv2 b/bin/currency-conv2
--- a/bin/currency-conv2
+++ b/bin/currency-conv2
@@ -1,88 +1,308 @@
 #!/bin/bash
 
-LIST="currency.list"
+LIST=":AED:ARE:United Arab Emirates Dirham:
+:AFN: :Afghan Afghani:
+:ALL:ALB:Albanian Lek:
+:AMD:ARM:Armenian Dram:
+:ANG:ANT:Netherlands Antillean Guilder:
+:AOA: :Angolan Kwanza:
+:ARS:ARG:Argentine Peso:
+:AUD:AUS:Australian Dollar:A$:
+:AWG:ABW:Aruban Florin:
+:AZN: :Azerbaijani Manat:
+:BAM: :Bosnia-Herzegovina Convertible Mark:
+:BBD:BRB:Barbadian Dollar:
+:BDT:BGD:Bangladeshi Taka:
+:BGN: :Bulgarian Lev:
+:BHD:BHR:Bahraini Dinar:
+:BIF:BDI:Burundian Franc:
+:BMD:BMU:Bermudan Dollar:
+:BND:BRN:Brunei Dollar:
+:BOB:BOL:Bolivian Boliviano:
+:BRL:BRA:Brazilian Real:R$:
+:BSD:BHS:Bahamian Dollar:
+:BTC: :Bitcoin:฿:
+:BTN:BTN:Bhutanese Ngultrum:
+:BWP:BWA:Botswanan Pula:
+:BYN: :Belarusian Ruble:
+:BYR: :Belarusian Ruble (2000–2016):
+:BZD:BLZ:Belize Dollar:
+:CAD:CAN:Canadian Dollar:CA$:
+:CDF: :Congolese Franc:
+:CHF: :Swiss Franc:
+:CLF: :Chilean Unit of Account (UF):
+:CLP: :Chilean Peso:
+:CNH: :CNH:
+:CNY: :Chinese Yuan:CN¥:
+:COP: :Colombian Peso:
+:CRC: :Costa Rican Colón:
+:CUP: :Cuban Peso:
+:CVE: :Cape Verdean Escudo:
+:CZK: :Czech Republic Koruna:
+:DEM: :German Mark:
+:DJF: :Djiboutian Franc:
+:DKK: :Danish Krone:
+:DOP: :Dominican Peso:
+:DZD: :Algerian Dinar:
+:EGP: :Egyptian Pound:
+:ERN: :Eritrean Nakfa:
+:ETB: :Ethiopian Birr:
+:EUR: :Euro:€:
+:FIM: :Finnish Markka:
+:FJD: :Fijian Dollar:
+:FKP: :Falkland Islands Pound:
+:FRF: :French Franc:
+:GBP: :British Pound:£:pund:
+:GEL: :Georgian Lari:
+:GHS: :Ghanaian Cedi:
+:GIP: :Gibraltar Pound:
+:GMD: :Gambian Dalasi:
+:GNF: :Guinean Franc:
+:GTQ: :Guatemalan Quetzal:
+:GYD: :Guyanaese Dollar:
+:HKD: :Hong Kong Dollar:
+:HNL: :Honduran Lempira:
+:HRK: :Croatian Kuna:
+:HTG: :Haitian Gourde:
+:HUF: :Hungarian Forint:
+:IDR: :Indonesian Rupiah:
+:IEP: :Irish Pound:
+:ILS: :Israeli New Shekel:₪:
+:INR: :Indian Rupee:₹:rupee:
+:IQD: :Iraqi Dinar:
+:IRR: :Iranian Rial:
+:ISK: :Icelandic Króna:
+:ITL: :Italian Lira:
+:JMD: :Jamaican Dollar:
+:JOD: :Jordanian Dinar::Dinar
+:JPY: :Japanese Yen:¥:yen:
+:KES: :Kenyan Shilling:
+:KGS: :Kyrgystani Som:
+:KHR: :Cambodian Riel:
+:KMF: :Comorian Franc:
+:KPW: :North Korean Won:
+:KRW: :South Korean Won:₩::won:
+:KWD: :Kuwaiti Dinar:
+:KYD: :Cayman Islands Dollar:
+:KZT: :Kazakhstani Tenge:
+:LAK: :Laotian Kip:
+:LBP: :Lebanese Pound:
+:LKR: :Sri Lankan Rupee:
+:LRD: :Liberian Dollar:
+:LSL: :Lesotho Loti:
+:LTL: :Lithuanian Litas:
+:LVL: :Latvian Lats:
+:LYD: :Libyan Dinar:
+:MAD: :Moroccan Dirham:
+:MDL: :Moldovan Leu:
+:MGA: :Malagasy Ariary:
+:MKD: :Macedonian Denar:
+:MMK: :Myanmar Kyat:
+:MNT: :Mongolian Tugrik:
+:MOP: :Macanese Pataca:
+:MRO: :Mauritanian Ouguiya:
+:MUR: :Mauritian Rupee:
+:MVR: :Maldivian Rufiyaa:
+:MWK: :Malawian Kwacha:
+:MXN: :Mexican Peso:MX$:
+:MYR: :Malaysian Ringgit:
+:MZN: :Mozambican Metical:
+:NAD: :Namibian Dollar:
+:NGN: :Nigerian Naira:
+:NIO: :Nicaraguan Córdoba:
+:NOK: :Norwegian Krone:
+:NPR: :Nepalese Rupee:
+:NZD: :New Zealand Dollar:NZ$:
+:OMR: :Omani Rial:
+:PAB: :Panamanian Balboa:
+:PEN: :Peruvian Sol:
+:PGK: :Papua New Guinean Kina:
+:PHP: :Philippine Peso:
+:PKG: :PKG:
+:PKR: :Pakistani Rupee:
+:PLN: :Polish Zloty:
+:PYG: :Paraguayan Guarani:
+:QAR: :Qatari Rial:
+:RON: :Romanian Leu:
+:RSD: :Serbian Dinar:
+:RUB: :Russian Ruble:
+:RWF: :Rwandan Franc:
+:SAR: :Saudi Riyal:
+:SBD: :Solomon Islands Dollar:
+:SCR: :Seychellois Rupee:
+:SDG: :Sudanese Pound:
+:SEK:SWE:Swedish Krona:kr:
+:SGD: :Singapore Dollar:
+:SHP: :St. Helena Pound:
+:SKK: :Slovak Koruna:
+:SLL: :Sierra Leonean Leone:
+:SOS: :Somali Shilling:
+:SRD: :Surinamese Dollar:
+:STD: :São Tomé Príncipe Dobra:
+:SVC: :Salvadoran Colón:
+:SYP: :Syrian Pound:
+:SZL: :Swazi Lilangeni:
+:THB: :Thai Baht:
+:TJS: :Tajikistani Somoni:
+:TMT: :Turkmenistani Manat:
+:TND: :Tunisian Dinar:
+:TOP: :Tongan Paʻanga:
+:TRY: :Turkish Lira:
+:TTD: :Trinidad &amp; Tobago Dollar:
+:TWD: :New Taiwan Dollar:NT$:
+:TZS: :Tanzanian Shilling:
+:UAH: :Ukrainian Hryvnia:
+:UGX: :Ugandan Shilling:
+:USD: USA:US Dollar:US$:$:dollar:
+:UYU: :Uruguayan Peso:
+:UZS: :Uzbekistani Som:
+:VEF: :Venezuelan Bolívar:
+:VND: :Vietnamese Dong:₫:
+:VUV: :Vanuatu Vatu:
+:WST: :Samoan Tala:
+:XAF: :Central African CFA Franc:FCFA:
+:XCD: :East Caribbean Dollar:EC$:
+:XDR: :Special Drawing Rights:
+:XOF: :West African CFA Franc:
+:XPF: :CFP Franc:CFPF:
+:YER: :Yemeni Rial:
+:ZAR: :South African Rand:
+:ZMK: :Zambian Kwacha (1968–2012):
+:ZMW: :Zambian Kwacha:
+:ZWL: :Zimbabwean Dollar (2009):"
 
 ColorOff='\033[0m'
 Color='\033[1;31m'
 
 #Flags
-flagSelf=false
 flagNewLine=false
+decimal=""
+delimiter=""
+raw=false
 
 currency() {
-    if ! [[ $1 = *[[:digit:]]* && $2 != "" && $3 != "" ]]; then
-        echo "Error" >&2
-        exit 3
-    fi
-    local f=false
+    local value=$1
+    local from=$2
+    local to=$3
 
+    # Check if amount is a nubber
+    if [[ $value == "" ]]; then
+        value=1 #defult amount 1
+    elif ! [[ $value = *[[:digit:]]* ]] ; then
+        echo "Error: Not a number" >&2
+        exit 2;
+    else
+        value="$(echo $value | bc -l)"
+    fi
+    
+    if ! [[ $value != "" && $from != "" && $to != "" ]]; then  
+        if [[ $value != "" && $from != "" ]]; then
+            to="SEK USD EUR GBP BTC"
+        elif [[ $value != "" ]]; then
+            from="SEK USD EUR GBP BTC"
+            to="SEK"  
+        fi
+    fi
+
+    local f=false
     #From
-    for m in $2; do
+    for m in $from; do
         #Get currency code
-        fList="$(grep -i ":$m:" $LIST)"        
+        fList="$(echo "$LIST" | grep -i ":$m:")"        
         if [ -z "$fList" ]; then
             echo "Error: Can't convert \"$m\""
             exit 5
         else
             fCode="$(echo "$fList" | cut -d':' -f2)"
         fi
-
+        
         #new line
         if [[ "$flagNewLine" == true && "$f" == true ]]; then echo ""; fi; f=true
-
+        
         #To
-        for n in $3; do
+        for n in $to; do
             #Get currency code
-            tList="$(grep -i ":$n:" $LIST)"        
+            tList="$(echo "$LIST" | grep -i ":$n:")"        
             if [ -z "$tList" ]; then
                 echo "Error: Can't convert \"$n\""
                 exit 5
             else
                 tCode="$(echo "$tList" | cut -d':' -f2)"
             fi
-
-
+            
+            
             if [[ "$fCode" != "$tCode" ]]; then
-                result="$(wget -qO- "http://www.google.com/finance/converter?a=$1&from=$fCode&to=$tCode" |  sed '/res/!d;s/<[^>]*>//g')";
+                result="$(wget -qO- "http://www.google.com/finance/converter?a=$value&from=$fCode&to=$tCode" |  sed '/res/!d;s/<[^>]*>//g')";
                 if [[ "$result" != "" ]]; then
-                    echo -ne "$Color$(echo -n $result | cut -d' ' -f1) $ColorOff"
-                    echo -ne "$(echo $result | cut -d' ' -f2-3)"
-                    echo -ne "$Color $(echo -n $result | cut -d' ' -f4) $ColorOff"
-                    echo -ne $result | cut -d' ' -f5-
+
+                    vfr=$(echo -n $result | cut -d' ' -f1)
+                    vto=$(echo -n $result | cut -d' ' -f4)
+                    if [[ "$decimal" != "" ]]; then
+                        vfr="$(echo $vfr | tr '.' "$decimal")"
+                        vto="$(echo $vto | tr '.' "$decimal")"
+
+                    fi
+                    if [[ "$delimiter" != "" ]]; then
+                        vfr="$(echo "$vfr" | sed ":a;s/\B[0-9]\{3\}\>/$delimiter&/;ta")"
+                        vto="$(echo "$vto" | sed ":a;s/\B[0-9]\{3\}\>/$delimiter&/;ta")"
+                    fi
+                    if [[ "$raw" != true ]]; then
+                        echo -ne "$Color$vfr$ColorOff"
+                        echo -ne " $(echo $result | cut -d' ' -f2-3)"
+                        echo -ne " $Color$vto$ColorOff"
+                        echo -e  " $(echo $result | cut -d' ' -f5-)"
+                    else
+                        echo -e "$vto"
+                    fi
                 else
                     echo "Error: Converting $fCode to $tCode" >&2
                 fi
             fi
-
             
-            #X -> X
-            if [[ "$fCode" == "$tCode" && "$flagSelf" == true ]]; then
-                echo -e "$Color$1$ColorOff $fCode = $Color$1$ColorOff $tCode"
-            fi
-
         done        
     done
 }
 
 HELP() {
-    echo -e "Help:\ncurrency-conv [OPTION]... [VALUE] [[FROM] [TO]]"
+    echo -e "Usage:
+ currency-conv [[options]... [VALUE] [ [FROM] [TO] ]]
+
+Currency converter
+
+Options:
+ -n, Add new line
+ -c, Remove collor
+ 
+ -l, List currencys 
+
+ -h, display this help and exit
+ -V, output version information and exit
+
+For more details see flock(1).
+"
     exit 0;
 }
 LIST() {
-    cat $LIST
+    echo "$LIST" | column -t -s":"
     exit 0;
+}
+VERSION() {
+    echo "currency-conv 0.1.2"
 }
 
 
-while getopts ':v:f:t:hlscn' flag; do
+while getopts ':v:f:t:s:d:hrlcnV' flag; do
   case "${flag}" in
 
     n) flagNewLine=true;;
-    s) flagSelf=true;;
-    c) Color='';;
+    c) Color=''; ColorOff='';;
+    d) decimal=${OPTARG};;
+    s) delimiter=${OPTARG};;
+    r) raw=true;;
 
     h) HELP;;
     l) LIST;;
+    V) VERSION;;
     
     v) value=${OPTARG};;
     f) from=${OPTARG};;
@@ -97,43 +317,31 @@ done
 shift $((OPTIND-1))
 
 
-
-
-args=( "$@" )
-n=0
-if [ -z "$value" ]; then
-   value="${args[$n]}"
-   ((n++))
-fi
-if [ -z "$from" ]; then
-   from="${args[$n]}"
-   ((n++))
-fi
-if [ -z "$to" ]; then
-   to="${args[$n]}"
-   ((n++))
-fi
-
-# Check if amount is a nubber
-if [[ $value == "" ]]; then
-    value=1 #defult amount 1
-elif ! [[ $value = *[[:digit:]]* ]] ; then
-   echo "Error: Not a number" >&2
-   exit 2
+if ! [ -t 0 ]; then
+    #stdin
+    while read -r line ; do
+        value="$(echo $line | cut -d' ' -f1)" 
+        from="$(echo $line | cut -d' ' -f2)"
+        to="$(echo $line | cut -d' ' -f3)"
+        currency $value $from $to
+    done
 else
-    value="$(echo $value | bc -l)"
+    args=( "$@" )
+    n=0
+    if [ -z "$value" ]; then
+        value="${args[$n]}"
+        ((n++))
+    fi
+    if [ -z "$from" ]; then
+        from="${args[$n]}"
+        ((n++))
+    fi
+    if [ -z "$to" ]; then
+        to="${args[$n]}"
+        ((n++))
+    fi
+    currency "$value" "$from" "$to"
 fi
-
-
-
-if [[ $value != "" && $from != "" && $to != "" ]]; then
-    currency $value "$from" "$to"
-elif [[ $value != "" && $from != "" ]]; then
-    currency $value "$from" "SEK USD EUR GBP BTC"
-elif [[ $value != "" ]]; then
-    currency $value "SEK USD EUR GBP BTC" "SEK"            
-fi
-
 
 
 
