Update currency converter to handle more input types and added color to out put.

diff --git a/bin/currency-conv2 b/bin/currency-conv2
--- a/bin/currency-conv2
+++ b/bin/currency-conv2
@@ -17,20 +17,31 @@ cur["btc"]="BTC"
 cur["bitcoin"]="BTC"
 cur["฿"]="BTC"
 
+ColorOff='\033[0m'
+Color='\033[1;31m'
 
 currency() {
-    if [[ $1 = *[[:digit:]]* && $2 != "" && $3 != "" ]]; then
-        c="${cur[${3,,}]}"
-        for n in $2; do
+    if ! [[ $1 = *[[:digit:]]* && $2 != "" && $3 != "" ]]; then
+        echo "Error" >2
+        exit 3
+    fi
+
+    for e in $2; do
+        c="${cur[${e,,}]}"
+        for n in $3; do
             b="${cur[${n,,}]}"
-            res="$(wget -qO- "http://www.google.com/finance/converter?a=$1&from=$b&to=$c" |  sed '/res/!d;s/<[^>]*>//g')";
+            res="$(wget -qO- "http://www.google.com/finance/converter?a=$1&from=$c&to=$b" |  sed '/res/!d;s/<[^>]*>//g')";
+ 
             if [[ $res != "" ]]; then
-                echo $res
+                echo -ne "$Color$(echo -n $res | cut -d' ' -f1) $ColorOff"
+                echo -ne "$(echo $res | cut -d' ' -f2-3)"
+                echo -ne "$Color $(echo -n $res | cut -d' ' -f4) $ColorOff"
+                echo -ne $res | cut -d' ' -f5-
             else
-                echo "$1 $b = $1 $c"
+                echo -e "$Color$1$ColorOff $b = $Color$1$ColorOff $c"
             fi
         done
-    fi
+    done
 }
 
 HELP() {
@@ -47,29 +58,56 @@ Bitcoin: \t BTC (฿)";
 }
 
 
-while getopts ':hl' flag; do
+while getopts ':v:f:t:hl' flag; do
   case "${flag}" in
     h) HELP;;
     l) LIST;;
+    
+    v) value=${OPTARG} ;;
+    f) from=${OPTARG}  ;;
+    t) to=${OPTARG}    ;;
+    
     *)
-        echo -e "Unexpected option ${flag}";
-        exit -1;
+        (>&2 echo -e "Unexpected option ${flag}");
+        exit 1;
         ;;
   esac
 done
+shift $((OPTIND-1))
+
+args=( "$@" )
+n=0
+if [ -z "$value" ]; then
+   value="${args[$n]}"
+   ((n++))
+fi
+if [ -z "$from" ]; then
+   from="${args[$n]}"
+   ((n++))
+fi
+if [ -z "$to" ]; then
+   to="${args[$n]}"
+   ((n++))
+fi
+
+# Check if amount is a nubber
+if ! [[ $value = *[[:digit:]]* ]] ; then
+   echo "error: Not a number" >&2
+   exit 2
+else
+    value="$(echo $value | bc -l)"
+fi
 
 
-if [[ $1 = *[[:digit:]]* && $2 != "" && $3 != "" ]]; then
-    c="$(echo $1 | bc -l)"
-    currency $c $2 $3
-elif [[ $1 = *[[:digit:]]* && $2 != "" ]]; then
-    c="$(echo $1 | bc -l)"
-    currency $c "SEK USD EUR GBP BTC" $2
-elif [[ $1 = *[[:digit:]]* ]]; then
-    c="$(echo $1 | bc -l)"
-    currency $c "SEK USD EUR GBP BTC" SEK            
-elif [[ $1 == "" ]]; then
-    currency 1 "SEK USD EUR GBP BTC" SEK
+
+if [[ $value != "" && $from != "" && $to != "" ]]; then
+    currency $value "$from" "$to"
+elif [[ $value != "" && $from != "" ]]; then
+    currency $value "SEK USD EUR GBP BTC" "$from"
+elif [[ $value != "" ]]; then
+    currency $value "SEK USD EUR GBP BTC" "SEK"            
+elif [[ $value == "" ]]; then
+    currency 1 "SEK USD EUR GBP BTC" "SEK"
 fi
 
 
